stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 include/polytools/polytools.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=g++-10
    - make
  artifacts:
    paths:
      - build/polytools_test
  
Test Polytools:
  stage: test
  tags:
    - bfs
  script:
    - ./build/polytools_test